<?php
/**
 * Email Configuration
 * IMPORTANT: Replace with your actual Gmail credentials
 * 
 * HOW TO GET GMAIL APP PASSWORD:
 * 1. Go to https://myaccount.google.com/security
 * 2. Enable 2-Step Verification if not already enabled
 * 3. Go to https://myaccount.google.com/apppasswords
 * 4. Select "Mail" and "Other (Custom name)"
 * 5. Generate the app password (16 characters)
 * 6. Copy and paste it below
 */

// Return configuration array directly (no constants to avoid conflicts)
return [
    'smtp_host' => 'smtp.gmail.com',
    'smtp_port' => 587, // Use 587 for TLS, 465 for SSL
    'smtp_username' => 'ihaveterminalcancer001@gmail.com', // ⚠️ Your Gmail address
    'smtp_password' => 'boyhjignlbmokvgw', // ⚠️ Your Gmail App Password (16 chars, no spaces)
    'from_email' => 'ihaveterminalcancer001@gmail.com', // ⚠️ Same as smtp_username
    'from_name' => 'Nexon IT Support',
    'enabled' => true, // Set to false to disable all emails
    'debug' => true // Set to true for debugging (will log more info)
];

/**
 * ⚠️ IMPORTANT NOTES:
 * 
 * 1. GMAIL APP PASSWORD:
 *    - This is NOT your regular Gmail password
 *    - It's a 16-character code generated by Google
 *    - Generate it at: https://myaccount.google.com/apppasswords
 *    - No spaces in the password (e.g., 'abcdefghijklmnop')
 * 
 * 2. REQUIREMENTS:
 *    - 2-Step Verification MUST be enabled on your Gmail account
 *    - Go to: https://myaccount.google.com/security
 *    - Enable "2-Step Verification" first
 *    - Then you can generate App Passwords
 * 
 * 3. TROUBLESHOOTING:
 *    - If you get "Invalid credentials" error:
 *      → Make sure you're using App Password, not regular password
 *      → Check that 2-Step Verification is enabled
 *      → Regenerate the App Password if needed
 * 
 *    - If you get "SMTP connect() failed":
 *      → Check your internet connection
 *      → Make sure port 587 is not blocked by firewall
 *      → Verify OpenSSL extension is enabled in PHP
 * 
 *    - If emails are not arriving:
 *      → Check spam/junk folder
 *      → Wait a few minutes (sometimes delayed)
 *      → Try sending to a different email address
 *      → Check if Gmail is blocking suspicious activity
 * 
 * 4. SECURITY:
 *    - NEVER commit this file with real credentials to Git
 *    - Add to .gitignore: classes/email_config.php
 *    - Use environment variables in production
 *    - Rotate App Passwords regularly
 * 
 * 5. TESTING:
 *    - Use the test tool: public/admin/test_email.php
 *    - Send to your own Gmail first
 *    - Check PHP error logs: C:\xampp\php\logs\php_error_log
 */